# Generated by Django 3.2.13 on 2022-06-06 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings_and_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('review', models.CharField(max_length=150)),
                ('ratings', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rice_list_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rice_name', models.CharField(max_length=50)),
                ('import_from', models.CharField(max_length=70)),
                ('about', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.ratings_and_review')),
            ],
        ),
        migrations.AddField(
            model_name='ratings_and_review',
            name='rice_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.rice_list_details'),
        ),
        migrations.AddField(
            model_name='ratings_and_review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Purchase_cart_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rice_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.rice_list_details')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
