# Generated by Django 3.2.13 on 2022-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_cart_detail',
            name='rice_selected',
        ),
        migrations.AddField(
            model_name='purchase_cart_detail',
            name='rice_selected',
            field=models.ManyToManyField(to='market.Rice_list_details'),
        ),
    ]
